### ISSUE TITLE
cmake support

### ISSUE THREAD

**Issue by bsergean** [aerospike/aerospike-client-c#107]
Hi there,

Has there been any cmake support request ever ? cmake support is good for parallel build with make or ninja generator, and windows support.

I tried to build this library with make -j but I got a few errors (which might be fixed in the latest code).

```
make[7]: *** No rule to make target 'modules/common/target/Linux-x86_64/include/aerospike/as_arraylist.h', needed by 'prepare'.  Stop.
make[7]: *** Waiting for unfinished jobs....
make[8]: *** No rule to make target '../../modules/common/target/Linux-x86_64/include/aerospike', needed by 'target/Linux-x86_64/lib/libmod_lua.a'.  Stop.
make[8]: *** Waiting for unfinished jobs....
project/modules.mk:97: recipe for target 'modules/mod-lua/target/Linux-x86_64/lib/libmod_lua.a' failed
make[7]: *** [modules/mod-lua/target/Linux-x86_64/lib/libmod_lua.a] Error 2
```

Thanks !

**Comment by BrianNichols** [comment]
Not that I can remember.  Full C client compile takes less than 1 minute on a laptop, so parallel make support has never been a priority.

**Comment by chouquette** [comment]
Hello, FWIW I opened a PR to solve parallel builds: https://github.com/aerospike/aerospike-client-c/pull/145

**Comment by bsergean** [comment]
Hey @BrianNichols is this completed as "won't fix" (which I understand), or as there's CMake support somewhere in a branch ?

**Comment by BrianNichols** [comment]
cmake is not supported.  C client 6.5.0 supports parallel make (make -j). That functional improvement made a cmake port unnecessary.
