### ISSUE TITLE
Unable to found benchmarks in aerospike-client-c

### ISSUE THREAD

**Issue by kish2010** [aerospike/aerospike-client-c#109]
I am trying to Get the Aerospike C client and benchmark tool from Github and followed all required steps from ReadMe file.

# **_git clone https://github.com/aerospike/aerospike-client-c_**
# _**cd aerospike-client-c/**_

After that I installed submodules by using below command:-
# _**git submodule update --init**_

followed with below steps:-
Make the C client and benchmark tool.
# _**make EVENT_LIB=libev**_
Set LD_LIBRARY
# e**_xport LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib_**

when I am trying to make benchmark tools, unable to get any benchmark in aerospike-client-c .

can someone help on this?

**Comment by kportertx** [comment]
The benchmark tool for the c client was moved to a separate repo: https://github.com/aerospike/aerospike-benchmark

**Comment by kish2010** [comment]
> The benchmark tool for the c client was moved to a separate repo: https://github.com/aerospike/aerospike-benchmark

Thanks kportertx. Issue is resolved with above repo.
