### ISSUE TITLE
Compile failed with "the clang compiler does not support '-march=nocona'"

### ISSUE THREAD

**Issue by yuanyal** [aerospike/aerospike-client-c#118]
Compiling on M1 Mac, 

Error log:
clang: error: the clang compiler does not support '-march=nocona'
make[8]: *** [target/Darwin-arm64/obj/common/aerospike/as_aerospike.o] Error 1
make[7]: *** [modules/common/target/Darwin-arm64/lib/libaerospike-common.a] Error 2
make[6]: *** [external_libs/src/project_aerospike-client-c-stamp/project_aerospike-client-c-build] Error 2
make[5]: *** [CMakeFiles/project_aerospike-client-c.dir/all] Error 2
make[4]: *** [CMakeFiles/project_aerospike-client-c.dir/rule] Error 2
make[3]: *** [project_aerospike-client-c] Error 2
make[2]: *** [built_external_third_party_libs.txt] Error 2
make[1]: *** [CMakeFiles/built_external_third_party_libs.dir/all] Error 2

Any suggestions on how to fix this? (how to remove -march=nocona?)

**Comment by bsergean** [comment]
If we remove this blob the problem goes away.

```
ifneq ($(ARCH),$(filter $(ARCH),ppc64 ppc64le))
CC_FLAGS += -march=nocona
endif
```

On Intel mac I get:

```
$ uname -m
x86_64
```

On an M1 mac we should get"

```
arm64
```

**Comment by yuanyal** [comment]
Issue resolved.
