### ISSUE TITLE
crash inside as_cluster_tend on arm64

### ISSUE THREAD

**Issue by bsergean** [aerospike/aerospike-client-c#121]
We are trying to get an arm64 build working on Apple Silicon, and we noticed this crash. The node isn't a null pointer, so it got corrupted somehow.

We know the arm port is underway, but maybe this can help in tracking things down.

```
Process 10437 stopped
* thread #6, stop reason = EXC_BAD_ACCESS (code=1, address=0x2f3a707474683352)
    frame #0: 0x0000000101b48eb0 mediationserver`as_cluster_tend(cluster=0x000000010a4cf200, err=0x00000001700b6b88, enable_seed_warnings=false) at as_cluster.c:693:17
   690 		
   691 		for (uint32_t i = 0; i < nodes->size; i++) {
   692 			as_node* node = nodes->array[i];
-> 693 			node->friends = 0;
   694 			node->partition_changed = false;
   695 			node->rebalance_changed = false;
   696 		}
(lldb) print node
(as_node *) $0 = 0x2f3a707474683286
```

**Comment by bsergean** [comment]
```
(lldb) print nodes->size
(uint32_t) $1 = 882914976
```

Everything is super corrupted.

**Comment by BrianNichols** [comment]
I don't currently have access to an M1 machine and the port to M1/ARM architectures has not started.  We do support pull requests if someone wants to assist, but it's important to set expectations that there are other projects that I need to work on that have higher priority.

**Comment by bsergean** [comment]
Thanks, understood. We'll see if we can make progress ourselves, but we also have our hands full.

**Comment by bsergean** [comment]
This was a one off with an odd build, so I'm gonna close this.
