### ISSUE TITLE
Release tagged 4.6.24 refers to missing .gitmodules

### ISSUE THREAD

**Issue by bsolomon-bw** [aerospike/aerospike-client-c#129]
https://github.com/aerospike/aerospike-client-c/releases/tag/4.6.24

https://github.com/aerospike/aerospike-client-c/blob/f813077e1ec702971733c47a4d86223fc0781e53/.gitmodules#L1-L16

`https://github.com/citrusleaf/aerospike-common` is 404.

**Comment by BrianNichols** [comment]
That particular release somehow kept the private submodule reference (citrusleaf).  I have checked-in a fix to the 4.6.X branch that restores the expected public submodule reference (aerospike).
