### ISSUE TITLE
aerospike-client-c link error with extra compiler flags -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer

### ISSUE THREAD

**Issue by baiyanhuang** [aerospike/aerospike-client-c#133]
I tried to build `aerospike-client-c` with frame pointer to fix a broken flamegraph I generated per https://brendangregg.com/FlameGraphs/cpuflamegraphs.html, with below command:
```
$ sudo make -j 1 EVENT_LIB=libevent O=1 "CFLAGS=-fno-omit-frame-pointer -mno-omit-leaf-frame-pointer"
```

But then I got errors:
```
modules/lua/src/loslib.o: In function `os_tmpname':
loslib.c:(.text+0x1b4): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
/usr/bin/ld: modules/lua/src/lapi.o: relocation R_X86_64_PC32 against symbol `lua_type' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Which complains about object file `modules/lua/src/lapi.o` is not compiled with `-fPIC` hence failed to be linked into `libaerospike.so`

It was perfectly fine without `-fno-omit-frame-pointer -mno-omit-leaf-frame-pointer`, and the link error is gone once I compile with `-fPIC`
```
sudo make -j 1 EVENT_LIB=libevent O=1 "CFLAGS=-fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC"
```
But does any body know why adding `-fno-omit-frame-pointer -mno-omit-leaf-frame-pointer` also calls for the addtion of `-fPIC`? 

The environment:
---
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

$ uname -a
Linux  5.4.0-100-generic #113~18.04.1-Ubuntu SMP Mon Feb 7 15:02:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ clang --version
Ubuntu clang version 12.0.1-++20211102090516+fed41342a82f-1~exp1~20211102211019.11
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by BrianNichols** [comment]
I don't know why `-fPIC` (generate position independent code) is required with `-fno-omit-leaf-frame-pointer`.  The referenced code is in the lua submodule which the C client uses, but does not modify.
