### ISSUE TITLE
Missing as_buffer.h in installed includes

### ISSUE THREAD

**Issue by burlog** [aerospike/aerospike-client-c#138]
I cloned repo and follow instruction `README.md` to install library.
```
$ git submodule update --init
$ make EVENT_LIB=libev
$ sudo make install
```
It worked great but when I tried compile project using it, I have got this error.
```
In file included from /usr/include/aerospike/as_async.h:20,
                 ...,
/usr/include/aerospike/as_command.h:20:10: fatal error: aerospike/as_buffer.h: No such file or directory
   20 | #include <aerospike/as_buffer.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by BrianNichols** [comment]
This will be fixed in the next C client release.  The workaround is to copy the include file to the installation directory:

sudo cp modules/common/src/include/aerospike/as_buffer.h /usr/include/aerospike
