### ISSUE TITLE
scan callback failing with memory fault issue

### ISSUE THREAD

**Issue by Shadab1990** [aerospike/aerospike-client-c#141]
Hi Team, I am getting memory segmentation error while running scan (concurrent is False) after scanning subset of records . Scan abruptly fails after processing few records so not sure what is causing this issue.

Below is the high level steps for the implemented code.

connection to aerospike server is made in main function
aerospike_scan_foreach is call with cb and connection pointer
in callback first we read the list of map under the scanned record PK and then reinsert the same after applying the as_hashmap_sort_flag to sort the list of map (this we do in overwrite mode)
Note: Failure is not specific to record it fails randomly. When we only scan then no issues but when we scan and perform read and write in callback then it fails after processing 150k records out of 200k.

Thanks

**Comment by BrianNichols** [comment]
I would need to see your scan source code to help.
