### ISSUE TITLE
Can't build this pkg

### ISSUE THREAD

**Issue by Eugene-Usachev** [aerospike/aerospike-client-c#157]
I installed this pkg on my Ubuntu. Next I tried to build it and got an error
`
project/modules.mk:16: ***************************************************************
project/modules.mk:17: *
project/modules.mk:18: *  COMMON is '/home/cake/products/excel_replacement/deps/aerospike-client-c/modules/common'
project/modules.mk:19: *  COMMON doesn't contain 'Makefile'.
project/modules.mk:20: *  COMMON should be set to a valid path.
project/modules.mk:21: *
project/modules.mk:22: ***************************************************************
project/modules.mk:23: *** .  Stop.
`

This error occured with both `make` and `make EVENT_LIB=libuv`. 

I looked at modules and found empty directories. Then I install them all and tried again. Even after the modules are installed, this error remains.

**Comment by BrianNichols** [comment]
This repository contains submodules that need to be initialized after cloning. To initialize:

`git submodule update --init`
