### ISSUE TITLE
Cannot compile this for HP UX

### ISSUE THREAD

**Issue by manojhirway** [aerospike/aerospike-client-c#17]
bash-4.3# make
Make: Must be a separator on rules line 5.  Stop.

Error comes from project/settings.mk file
###### 
###### 

export CFLAGS=-Wall ------------------> Line 5
export LDFLAGS=" "
export ARFLAGS=" "

Has anyone tried to compile the client or server on HPUX or AIX platforms ? Am I missing something here ?

**Comment by BrianNichols** [comment]
HPUX and AIX are not currently supported.
