### ISSUE TITLE
Usage in C++ code requires wrapping headers in extern "C"

### ISSUE THREAD

**Issue by bb-avn** [aerospike/aerospike-client-c#19]
We include the Aerospike client libraries in a C++ project. In order to avoid linker errors, every file that includes an `#include` directive for an Aerospike header needs to wrap those in an `extern "C"` block like this:

```C
// Aerospike -- WARNING - extern "C" required!
extern "C" {
#include <aerospike/aerospike.h>
#include <aerospike/aerospike_key.h>
#include <aerospike/aerospike_query.h>
#include <aerospike/aerospike_lmap.h>
#include <aerospike/aerospike_index.h>
}
```

Could the Aerospike client library header files be made C++-safe by including this in the headers themselves?

**Comment by BrianNichols** [comment]
This will be added in the next C client release.

**Comment by BrianNichols** [comment]
Aerospike C client 3.1.0 has been released.
