### ISSUE TITLE
Compile library for iOS SDK

### ISSUE THREAD

**Issue by LyahovchukS** [aerospike/aerospike-client-c#20]
Hello. 
I compile your 'aerospace-client-c' (library 'libaerospike.a') for iOS SDK, but I have an error
![2015-03-10 13 06 29](https://cloud.githubusercontent.com/assets/7487003/6573723/5e482e5c-c726-11e4-80bf-5f1708d194ab.png)
What is wrong?

**Comment by LyahovchukS** [comment]
May be i set wrong architecture?
![2015-03-10 13 11 59](https://cloud.githubusercontent.com/assets/7487003/6573811/5386506a-c727-11e4-8724-4e1b8e63b308.png)

**Comment by BrianNichols** [comment]
We support/test Mac OSX (not IOS).

I recommend opening "project/client.xcworkspace" in Xcode and compiling aerospike-test project.  If that compiles, then I recommend using the same architecture targets in your application.
