### ISSUE TITLE
Can't compile with make -j >1

### ISSUE THREAD

**Issue by ultrabug** [aerospike/aerospike-client-c#22]
I haven't been able to isolate the culprit but it's fairly easy to reproduce, just try to build using `make -j4` and see.

**Comment by BrianNichols** [comment]
"make -j" is not supported.  We tried adding ".NOTPARALLEL" at various levels in our Makefile, but it was  not successful for all j values on all platforms.   It's clear that there is no simple solution to only parallelize sections that can be parallelized.  We welcome contributions to our Makefiles that result in shorter make execution times.

**Comment by ultrabug** [comment]
Well I can't guarantee that I'll spare some time for this as I'm far from being a C/autotools expert but I'm quite surprised by your answer since this repository does not look that huge.

Anyway, I hope someone more competent than me will eventually fix this someday. Cheers.
