### ISSUE TITLE
Ability to control (de)serialization on all requests

### ISSUE THREAD

**Issue by arthurprs** [aerospike/aerospike-client-c#23]
This is specially useful/efficient when using the C client as a basis to other language clients, as in the Python client. By being able to bypass the deserialization on the requests the python library can deserialize the msgpack directly into python objects, pretty much halving memory allocations and iterations. The same applies for serialization.

Right now you can only control complex type deserialization on scan requests via as_scan.deserialize_list_map = false. It'd be great to support the same for get and query, the infrastructure it's already in place for that. We just need a way to pass this down to the last param of as_command_parse_bins.

As for serialization on put, there's no real infrastructure in place for it, but we can easily add two new types, as_rawlist and as_rawmap that just point their buffer to the already serialized msgpack data. This can even go into the external client.

Am I missing something? Is this something you guys want?

**Comment by BrianNichols** [comment]
There is an alternate implementation that is already supported.  On writes, you can serialize your data to an as_bytes value before calling aerospike_key_put().  as_bytes_init_wrap() can be used to wrap a serialized byte array without reallocation.

On reads, you will receive an as_bytes value.  Then, you can deserialize from that or not.

**Comment by arthurprs** [comment]
That's a reasonable alternative but by using the internal (map, list) types you get better compatibility across drivers, human readable aql output, secondary indexes support and other advantages.

**Comment by BrianNichols** [comment]
We have decided the add support for external serialization/deserialization in the next C client release.

**Comment by arthurprs** [comment]
Wow, that's great news.

**Comment by BrianNichols** [comment]
Version 3.1.19 has been released.
