### ISSUE TITLE
Compilation on ppc64le

### ISSUE THREAD

**Issue by bpaquet** [aerospike/aerospike-client-c#25]
Hi,

Any plan to allow compilation of aerospike client, without lua, on ppc64le ?

Regards,

Bertrand

**Comment by bpaquet** [comment]
Concurrency kit build is ok under ppc64le.
LuaJit is not needed for my need.
The only remaining __asm__ code is in common/src/include/citrusleaf/cf_atomic.h.

Any idea to implement this few functions with ppc64 asm instructions ?

**Comment by wchu-citrusleaf** [comment]
Currently there is no plan to support ppc64le.

**Comment by BrianNichols** [comment]
The latest C client has re-implemented those cf_atomic functions with concurrency kit functions.

**Comment by bpaquet** [comment]
The last version of c and php drivers compile and works on ppc64 LE.
