### ISSUE TITLE
Connect to bad cluster after historic fall when using shm

### ISSUE THREAD

**Issue by jarda-manana** [aerospike/aerospike-client-c#27]
I have run into issue, when client connect to another cluster because of fall (sigsegv) in past:
 
I'm connecting to a cluster with shm enabled:

```
cfg.use_shm = true;
cfg.shm_takeover_threshold_sec=1;
```
 
Let's connect to first cluster and fall due to sigsegv:
```
$> ./sigsegv 10.0.23.9
zsh: segmentation fault (core dumped)  ./sigsegv 10.0.23.9
```
 
shared memory is allocated:
```
$> ipcs -m | grep 0xa5
0xa5000000 51642414   jarda      666        263224
```
 
Now let's connect to another cluster with repaired binary (same config, but another cluster):
```
$> ./info 10.0.17.89
 
aerospike_info_any response ok: service	10.0.23.9:3000
aerospike_info_any response ok: service	10.0.23.9:3000
aerospike_info_any response ok: service	10.0.23.9:3000
aerospike_info_any response ok: service	10.0.23.9:3000
aerospike_info_any response ok: service	10.0.23.9:3000
```
 
The cluster, that is answering is the old one (**10.0.23.9**), but I wanted to seed cluster from **10.0.17.89**.
I understand first line - there is a shared memory, so client doesn't need to ask cluster. But in config I set `cfg.shm_takeover_threshold_sec=1`, so after 1 s, there should be new cluster reached.
 
Source codes of binaries: https://gist.github.com/jarda-manana/053be1411c24ae4cbdcf, C Client Library 3.1.22

**Comment by BrianNichols** [comment]
Different clusters should never share the same shared memory key (0xa5000000).  You can solve this one of two ways:

1) Remove old shared memory segment. 
```
sudo ipcrm -M 0xa5000000
```
The next info program will automatically create a new shared memory segment for the new cluster.

2) Use a different shared memory key for the second cluster.
```
cfg.use_shm = true;
cfg.shm_key = 0xA6000000;
```
You will need to pass the shared memory key as a command line argument to your info program.

**Comment by jarda-manana** [comment]
Thanks for answer. that's clear.
If there is only one cluster, will takeover thread maintain the cluster state? I was worry about it, when cluster change wasn't recognised.

**Comment by tivvit** [comment]
I ran into same problem in python, where `cfg.shm_key = 0xA6000000;` cannot be used. 
I was connecting to localhost, while another running process was connected to some cluster, and I was connected to the cluster instead of localhost. Both apps are using   `shm`.
I get that this behaviour is probably wanted, on the other side those are separate clusters, it would be nice to be informed somehow that I have been connected to cluster in which isn't contained server listed in configuration.

**Comment by rbotzer** [comment]
It's an issue in progress on the Python client (AER-4384) and the PHP client (AER-4385).

**Comment by BrianNichols** [comment]
*If there is only one cluster, will takeover thread maintain the cluster state?*

Yes.  The new process will take over cluster tending using the existing shared memory cluster nodes.

**Comment by jarda-manana** [comment]
@BrianNichols thanks for answer, closing this.
