### ISSUE TITLE
cf_atomic.h is not compatible with POWERPC

### ISSUE THREAD

**Issue by mlpesant** [aerospike/aerospike-client-c#35]
I am working on porting aerospike to POWERPC and fc_atomic.h has embedded x86 assembly.  I changed 2 header files, 3 Makefiles, and updated the ck subdirectory to get the workload to compile for POWER.  I would like to check in this code so I can run it with PerfKitBenchmarker.
I followed the process outlined by PerfKitBenchmarker/CONTRIBUTING.md to push code but I got a permission denied error.  How should I go about submitting this code?  Thanks!
```
mlpesant@tul65p1:~/aerospike-client-c$ git push origin ppc64
Username for 'https://github.com': mlpesant
Password for 'https://mlpesant@github.com': 
remote: Permission to aerospike/aerospike-client-c.git denied to mlpesant.
fatal: unable to access 'https://github.com/aerospike/aerospike-client-c.git/': The requested URL returned error: 403
```

**Comment by BrianNichols** [comment]
aerospike-client-c does not allow direct branching.  You will need to fork the repository and then make a pull request (Click "Fork" icon in upper right hand corner on aerospike-client-c github page).

Note that "aerospike/ck" is just a copy of the concurrencykit repository include files with some minor changes.  

[ConcurrencyKit](https://github.com/concurrencykit/ck)

I suggest submitting a pull request to the ConcurrencyKit too.  That way, both repos can stay in sync.

**Comment by BrianNichols** [comment]
Also, which version of aerospike-client-c are you using?  The assembly code in cf_atomic.h was replaced  with ConcurrenyKit methods over 6 months ago.  See:

https://github.com/citrusleaf/aerospike-common/blob/master/src/include/citrusleaf/cf_atomic.h

**Comment by mlpesant** [comment]
@BrianNichols, thanks for your response.  It took me a little while to get this figured out, but I committed a change to aerospike-client-c/Makefile yesterday and then pushed it with the command
`git push origin ppc64`
I then tried to do a pull request, but it says there's nothing to compare.  Will my change make it in or is there something else I need to do?  Thanks a lot for your help.  I'm still learning how to work with git and the open source community.

**Comment by BrianNichols** [comment]
The pull requests were all received.  The aerospike-client-c and aerospike-mod-lua pull requests had the correct Makefile change.  The aerospike-common pull request had lots of changes that clearly was crafted from a very old version.  I modified aerospike-common to only include the Makefile change.

**Comment by BrianNichols** [comment]
C client 4.0.4 has been released.
