### ISSUE TITLE
Tarballs on github are incomplete

### ISSUE THREAD

**Issue by patricklauer** [aerospike/aerospike-client-c#37]
Thanks to usage of git submodules ... 

Build fails with
`find: ‘/var/tmp/portage/dev-libs/libaerospike-4.0.4/work/aerospike-client-c-4.0.4/modules/common/src/include/aerospike/ck’: No such file or directory`
since obviously that directory in the tarballs is empty.

Would be very convenient to have proper release tarballs available ...

**Comment by BrianNichols** [comment]
What are the commands you are using to build?   "make package"?
Did you try "git submodule update --init"? 
Are you building in the git repository or the extracted tgz archive?

**Comment by patricklauer** [comment]
The tarballs provided by github ( https://github.com/aerospike/aerospike-client-c/archive/4.0.4.tar.gz for example, to be found in code -> releases ) are, as usual for GH (not the first time I encounter this) incomplete. 
`git submodule ...` can't work since this is a stripped down tarball without any git metadata.
And all directories populated with git submodules are empty.

(So currently the only way to build a specific release would be to checkout the git repo and then rewind it to a specific commit, which is quite silly)

**Comment by wchu-citrusleaf** [comment]
We will look into providing the src tarball on our download directory. For the mean time, best to git checkout specific tags for the supported releases. Thanks.

**Comment by vertexclique** [comment]
`cf_byte_order.h` is also not present in both `macos` and `linux` distribs.

**Comment by aknuds1** [comment]
I tried to build the 4.3.19 source tarball on OS X.
```
$ ./xcode/prepare_xcode
Updating Homebrew...
Warning: wget 1.19.5 is already installed and up-to-date
To reinstall 1.19.5, run `brew reinstall wget`
Warning: automake 1.16.1_1 is already installed and up-to-date
To reinstall 1.16.1_1, run `brew reinstall automake`
Warning: libtool 2.4.6_1 is already installed and up-to-date
To reinstall 2.4.6_1, run `brew reinstall libtool`
Warning: openssl 1.0.2p is already installed and up-to-date
To reinstall 1.0.2p, run `brew reinstall openssl`
./xcode/prepare_xcode: line 16: cd: modules/lua/src: No such file or directory
make: *** No rule to make target `macosx'.  Stop.
The file /Users/arve/xcode/client.xcworkspace does not exist.
```

**Comment by BrianNichols** [comment]
Github does not include submodules in their tarballs.  We have no control over how they generate those tarballs.

You will need to clone the repo and then pull in the submodules:

```
git clone https://github.com/aerospike/aerospike-client-c.git
cd aerospike-client-c
git submodule update --init
```

**Comment by aknuds1** [comment]
Is it possible to avoid serving these tarballs on GitHub? It's confusing
since you would think they would work.

**Comment by BrianNichols** [comment]
No.  We have no way to disable those tarballs.
