### ISSUE TITLE
With use_shm=true client prints info request to stdout

### ISSUE THREAD

**Issue by jhecking** [aerospike/aerospike-client-c#38]
With shared memory enabled, the client sometimes dumps what looks like an info request string prefixed with "#" to stdout:

    $ ./test
    Connected to cluster
    #node
    partition-generation
    services

The string after the "#" matches the info request string defined in INFO_STR_CHECK at as_node.c:592.

This is the simple test program with which I am able to reproduce the issue:

````
#include "aerospike/aerospike.h"

int main()
{
	as_error err;

	as_config config;
	as_config_init(&config);
	as_config_add_host(&config, "192.168.33.10", 3000);
	config.use_shm = true;
	config.shm_key = 0xa5000000;

	aerospike as;
	aerospike_init(&as, &config);
	if (aerospike_connect(&as, &err) != AEROSPIKE_OK) {
		fprintf(stderr, "error(%d) %s at [%s:%d]", err.code, err.message, err.file, err.line);
	}

	printf("Connected to cluster\n");
	sleep(60);

	if (aerospike_close(&as, &err) != AEROSPIKE_OK) {
		fprintf(stderr, "error(%d) %s at [%s:%d]", err.code, err.message, err.file, err.line);
	}
}
````

The issue seems to only occur if I terminate the program early, before the call to `aerospike_close`, and then run it again. The string also doesn't get dumped immediately; it seems to happen once the lock on the shared memory segment expires.

**Comment by BrianNichols** [comment]
This has been fixed in the latest C client (4.0.5).
