### ISSUE TITLE
Cleanup is not finished on return from aerospike_close when using libuv

### ISSUE THREAD

**Issue by XeCycle** [aerospike/aerospike-client-c#41]
The [uv code](https://github.com/aerospike/aerospike-client-c/blob/master/src/main/aerospike/as_event_uv.c#L657-L662) queues up closing of connections but the [ev code](https://github.com/aerospike/aerospike-client-c/blob/master/src/main/aerospike/as_event_ev.c#L577-L578) closes immediately.  As a result, when using libuv, a return from `aerospike_close` still leaves open connections to be closed, which will be executed on later loop iterations; but at this point it is unsafe to call `as_event_close_loops` from one of the loop threads, because a loop will be [closed immediately if detected to be on the same thread as the caller](https://github.com/aerospike/aerospike-client-c/blob/master/src/main/aerospike/as_event.c#L150-L153), and pending connections will be leaked.

Btw. in uv the aerospike_close -> aerospike_destroy -> as_event_close_loops process gives me a segfault in trying to unlock a mutex at [the end](https://github.com/aerospike/aerospike-client-c/blob/master/src/main/aerospike/as_event_uv.c#L702); I am not sure if these are related, but if I skip that thread == current thread check and blindly queue up the close command, it works fine.

**Comment by BrianNichols** [comment]
I agree.  `as_event_close_loops()` should always queue the event loop close, so it can't get executed before previous queued commands (like socket close).  We will fix in the next release.

The segfault is related.  When closing event loops directly, `pthread_mutex_unlock()` is called on a unlocked mutex.  This results in undefined behavior.

Queued event loop close is processed under a lock.  In this case, `as_event_close_loop()` correctly calls `pthread_mutex_unlock()` to release the lock after resources are released.

**Comment by BrianNichols** [comment]
C client  4.0.7 now always queues the event loop close.
