### ISSUE TITLE
aerospike-client-c does not resize thread pool size if needed

### ISSUE THREAD

**Issue by thomas-activevideo** [aerospike/aerospike-client-c#44]
First, here is some background. We use the Client library as part of our client database backend of our application. This is the first context of utilisation of the Client library. The default value of the thread pool size is set to 16. Each process of our application had 30+ running threads linked to the Aerospike backend default configuration. Our application spawns client processes and hit the maximum thread limit because of the overall number of threads present on the machine.

We needed to reduce the number of threads in this first context. We then reduced the thread pool size to one thread while initialising Aerospike in our application, static initialisation. 

The Client library is used in a second context where we observed hanging behaviour while examining the poolstats because of the load inherent to a single work thread executing the queries. In this second context, we would expect more threads to be created to cope with the load. Furthermore, we noticed that, in the Client library, the thread pool size is not resized with the function as_thread_pool_resize from the library aerospike-common.

Why is the thread pool not resize upon load balancing needs? We would like the Client library to resize the thread pool size if needed.

Details:  We run our application on CentOS 7.2 with the following packages:

```
Name        : aerospike-client-c
Version     : 4.0.6

Name        : aerospike-client-c-devel
Version     : 4.0.6

Name        : aerospike-server-community
Version     : 3.8.4

Name        : aerospike-tools
Version     : 3.8.3
```

**Comment by BrianNichols** [comment]
The thread pool is not designed to automatically detect load and adjust thread pool size accordingly.  That would be a much more complex implementation.  

Synchronous batch/scan/query are the only commands that use this thread pool.  These commands subdivide into subcommands for each server node so they can be run in parallel.  The thread pool is used to run these subcommands.

The thread pool size is configured per each aerospike client instance.  Different client processes can have different thread pool sizes at instance creation.

It's important for the user to size the pool according to how many concurrent batch/scan/query commands need to run concurrently on that instance.  If the cluster size is 8 and at least 4 batch/scan/queries need to run in parallel, then the thread pool size should be 32 (8 * 4).

The thread pool implementation is shared with server.  as_thread_pool_resize() is only called by the server when batch thread size is modified by the user via an info command on a running server.

**Comment by thomas-activevideo** [comment]
Thanks for the answer. It is clearer.

We circumvented the hanging issue by defining a different thread pool size per aerospike client instance. A small thread pool size (1 thread) for the first context mentioned and a larger size (default value so 16 threads) for solving the hanging issue in the second context.
