### ISSUE TITLE
A potential memory leak

### ISSUE THREAD

**Issue by XeCycle** [aerospike/aerospike-client-c#45]
https://github.com/aerospike/aerospike-client-c/blob/master/src/main/aerospike/as_info.c#L255
If the read above failed, `response` would leak.

**Comment by BrianNichols** [comment]
That is a bug.  We will fix in the next client release.

**Comment by BrianNichols** [comment]
C client 4.1.1 has been released.

http://www.aerospike.com/download/client/c/4.1.1/
