### ISSUE TITLE
The macro as_bins_inita might allocate not enough memory

### ISSUE THREAD

**Issue by emironov** [aerospike/aerospike-client-c#46]
There is a dangerous calculation of the memory size in the macro 'as_bins_inita':

``` cpp
#define as_bins_inita(__bins, __capacity) \\
        (__bins)->_free = false;\\
        (__bins)->capacity = __capacity;\\
        (__bins)->size = 0;\\
        (__bins)->entries = (as_bin *) alloca(sizeof(as_bin) * __capacity);
```

__capacity might be an expression (e.g. 5 + vec.size()). In this case, the size of allocated memory will be calculated incorrect:

``` cpp
 (__bins)->entries = (as_bin *) alloca(sizeof(as_bin) * 5 + vec.size()); // The order will be: ( (sizeof(as_bin) * 5) + vec.size() )
```

The  correct version might look like this:

``` cpp
#define as_bins_inita(__bins, __capacity) \
        (__bins)->_free = false;\
        (__bins)->capacity = __capacity;\
        (__bins)->size = 0;\
        (__bins)->entries = (as_bin *) alloca(sizeof(as_bin) * ((__bins)->capacity));
```

**Comment by BrianNichols** [comment]
I think using parenthesis around __capacity is a slightly better solution since the capacity will usually be a single variable.  The compiler will probably optimize either solution.  This will be fixed in the next release.

**Comment by BrianNichols** [comment]
C client 4.1.2 has been released.
