### ISSUE TITLE
as_record bins reallocation

### ISSUE THREAD

**Issue by maxim-ky** [aerospike/aerospike-client-c#51]
Hi guys,

The documentation (http://www.aerospike.com/apidocs/c/df/dd6/structas__record.html) says that `as_record_init` caller could pass `nbins` == 0 if the number of bins to initialize is unknown. I guess it implies that the desired number of bins would be allocated later (like in `std::vector`). But in fact, there is no reallocation logic in `as_record_bin_forupdate`.

I'm wondering whether it's an issue or this behavior is considered to be correct.

**Comment by BrianNichols** [comment]
The documentation is wrong.  Record bins are not resizable.  We will fix the documentation.

**Comment by BrianNichols** [comment]
C client 4.1.3 has been released.
