### ISSUE TITLE
SSLv3_client_method is not available on Debian Stretch

### ISSUE THREAD

**Issue by vytas-dauksa** [aerospike/aerospike-client-c#53]
Debian Stretch builds openssl with no-sslv3-method flag, hence SSLv3_client_method is no longer available, which is used here ( https://github.com/aerospike/aerospike-client-c/blob/master/src/main/aerospike/as_tls.c#L493 ). So linker fails when compiling against it:
[..] libaerospike.so: undefined reference to 'SSLv3_client_method'

**Comment by BrianNichols** [comment]
Is there a pre-defined macro that identifies Debian Stretch?

We could then not call SSLv3_client_method when this macro is defined.

**Comment by vytas-dauksa** [comment]
You should be able to rely on OPENSSL_NO_SSL3_METHOD

**Comment by BrianNichols** [comment]
We will add the following when SSLV3 is chosen in the next C client release:

```
#ifndef OPENSSL_NO_SSL3_METHOD
    method = SSLv3_client_method();
#else
    cert_blacklist_destroy(cert_blacklist);
    return as_error_update(errp, AEROSPIKE_ERR_TLS_ERROR, "SSLV3 protocol is not allowed");
#endif
```

**Comment by BrianNichols** [comment]
C client 4.1.4 has been released:

http://www.aerospike.com/download/client/c/4.1.4/

**Comment by indroid378** [comment]
> Debian Stretch builds openssl with no-sslv3-method flag, hence SSLv3_client_method is no longer available, which is used here ( https://github.com/aerospike/aerospike-client-c/blob/master/src/main/aerospike/as_tls.c#L493 ). So linker fails when compiling against it:
> [..] libaerospike.so: undefined reference to 'SSLv3_client_method'

what is i'm change?
apache or libssl?

thank you
