### ISSUE TITLE
Compile error on ubuntu14

### ISSUE THREAD

**Issue by Steve888888** [aerospike/aerospike-client-c#59]
cc -Isrc/include -Imodules/common/target/Linux-x86_64/include -Imodules/mod-lua/target/Linux-x86_64/include -Imodules/lua/src -std=gnu99 -g -Wall -fPIC -O3 -fno-common -fno-strict-aliasing -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_GNU_SOURCE -march=nocona -finline-functions -rdynamic -o target/Linux-x86_64/obj/aerospike/as_tls.o -c src/main/aerospike/as_tls.c
src/main/aerospike/as_tls.c: In function \u2018as_tls_thread_cleanup\u2019:
src/main/aerospike/as_tls.c:369:2: warning: \u2018ERR_remove_state\u2019 is deprecated (declared at /usr/local/include/openssl/err.h:248) [-Wdeprecated-declarations]
  ERR_remove_state(0);
  ^
src/main/aerospike/as_tls.c: In function \u2018verify_callback\u2019:
src/main/aerospike/as_tls.c:417:25: error: dereferencing pointer to incomplete type
  if (current_cert == ctx->cert) {
                         ^
src/main/aerospike/as_tls.c:426:39: error: dereferencing pointer to incomplete type
   bool matched = as_tls_match_name(ctx->cert, hostname, allow_wildcard);
                                       ^
src/main/aerospike/as_tls.c: In function \u2018as_tls_context_setup\u2019:
src/main/aerospike/as_tls.c:493:3: warning: implicit declaration of function \u2018SSLv3_client_method\u2019 [-Wimplicit-function-declaration]
   method = SSLv3_client_method();
   ^
src/main/aerospike/as_tls.c:493:10: warning: assignment makes pointer from integer without a cast [enabled by default]
   method = SSLv3_client_method();
          ^
src/main/aerospike/as_tls.c:496:3: warning: \u2018TLSv1_client_method\u2019 is deprecated (declared at /usr/local/include/openssl/ssl.h:1591) [-Wdeprecated-declarations]
   method = TLSv1_client_method();
   ^
src/main/aerospike/as_tls.c:499:3: warning: \u2018TLSv1_1_client_method\u2019 is deprecated (declared at /usr/local/include/openssl/ssl.h:1597) [-Wdeprecated-declarations]
   method = TLSv1_1_client_method();
   ^
src/main/aerospike/as_tls.c:502:3: warning: \u2018TLSv1_2_client_method\u2019 is deprecated (declared at /usr/local/include/openssl/ssl.h:1603) [-Wdeprecated-declarations]
   method = TLSv1_2_client_method();
   ^
src/main/aerospike/as_tls.c: At top level:
src/main/aerospike/as_tls.c:255:1: warning: \u2018pthreads_locking_callback\u2019 defined but not used [-Wunused-function]
 pthreads_locking_callback(int mode, int type, const char *file, int line)
 ^
src/main/aerospike/as_tls.c:265:1: warning: \u2018pthreads_thread_id\u2019 defined but not used [-Wunused-function]
 pthreads_thread_id(CRYPTO_THREADID *tid)
 ^
make: *** [target/Linux-x86_64/obj/aerospike/as_tls.o] Error

**Comment by BrianNichols** [comment]
I suspect that you have the wrong version openssl installed.  Try this command:

```
dpkg -l |grep openssl
```
The openssl version should be at least 1.0.1f

```
ii  openssl                             1.0.1f-1ubuntu2.8                amd64        Secure Sockets Layer toolkit - cryptographic util
```

Also try reinstalling openssl:

```
sudo apt-get install libssl-dev
```
