### ISSUE TITLE
server connection error

### ISSUE THREAD

**Issue by lathakris** [aerospike/aerospike-client-c#60]
I had a quick question on handling server connection errors. I have a persistent connection to the aerospike server. I keep doing read/writes. 
Is there a specific error code which gets set when the server becomes unavailable ? We do scaling and shrinking of aerospike servers  and when this error happens I can disconnect and reconnect back to the active list at that point in time.
I was thinking I can look for - AEROSPIKE_ERR_CONNECTION  code which gets set in as_error.code ?
But I see that when the initial connection fails due to down server, the code is set to - AEROSPIKE_ERR_CLIENT ?

Could you please clarify. Thank you.

**Comment by BrianNichols** [comment]
AEROSPIKE_ERR_CONNECTION returned on sync transaction connection errors.
AEROSPIKE_ERR_ASYNC_CONNECTION returned on async transaction connection errors.
AEROSPIKE_ERR_CLIENT returned when all seed connections fail on startup.

**Comment by lathakris** [comment]
Thank you so much for your response. I am using sync transactions. I will check for AEROSPIKE_ERR_CONNECTION
