### ISSUE TITLE
git master branch history change?

### ISSUE THREAD

**Issue by darkcrawler01** [aerospike/aerospike-client-c#66]
We notice that the git history for `master` branch has been re-written recently
This has caused different SHAs for the same commit

eg.  https://github.com/aerospike/aerospike-client-c/commit/894081994434bb2a54be2cc98777026c9260a237 has been orphaned and https://github.com/aerospike/aerospike-client-c/commit/3d25bfef9e19482499b43866644b1b7e47ca073d has replaced this commit.

Was this repo `rebase`d in a breaking way?

**Comment by BrianNichols** [comment]
We maintain a private aerospike-client-c repo.  On every release, the public aerospike-client-c repo is erased and the private repo's master branch is copied to the public repo.
