### ISSUE TITLE
deb package

### ISSUE THREAD

**Issue by ciklysta** [aerospike/aerospike-client-c#68]
Hello,

Following is a bugreport / wishlist / improvement proposal.

We have *aerospike-client-c\** and *python-aerospike* in our company's local deb repository. I've noticed that the Debian packages are conflicting. I can not install *aerospike-client-c* and *aerospike-client-c-devel* at the same time. This causes problems when packaging. I want my package to have a build dependency on the *dev* package and a runtime dependency on the *lib* package. This is how every other package is made. Will you consider creating nonconflicting *libaerospike3* and *aerospike-client-dev* packages (and their non-blocking alternatives)? The *lib* package would contain only .so and .lua files and the *dev* package would contain header files and a static library. I can create a pull request if you are interested.

And another question is: do you guarantee ABI stability (no backward incompatible changes) across one application major version? In other words can I safely link against one .so, e.g. create a python-aerospike debian package with dependency aerospike-client-c=3, and will it correctly work with any 3.* version without recompiling? I'm asking because I was told that some my colleagues hit this problem with incompatibility some time ago. If you don't gurantee it, there is only one viable option how to distribute it  and it is a static library. 

Thank you

**Comment by BrianNichols** [comment]
Yes, we would welcome a pull request.

No, we don't guarantee ABI stability across versions.  There are many cases where we need to add extra fields to structures and this requires a recompile.

**Comment by BrianNichols** [comment]
C client 4.1.7 changed the package layout.

http://www.aerospike.com/download/client/c/4.1.7/

Header files and static library are now located in devel packages.  Lua files and dynamic shared library are located in runtime packages.
