### ISSUE TITLE
Can't compile due to the following error.

### ISSUE THREAD

**Issue by akayami** [aerospike/aerospike-client-c#69]
error: dereferencing pointer to incomplete type ‘X509_STORE_CTX {aka struct x509_store_ctx_st}’

A quick google points me to other projects running into issues with openssl 1.1.0. 

I'm trying to do this on arch, and my open ssl version is: OpenSSL 1.1.0f

Thanks.

**Comment by BrianNichols** [comment]
We will support OpenSSL 1.1.x in the next release.

**Comment by BrianNichols** [comment]
C client 4.1.7 supports OpenSSL 1.1.x.

http://www.aerospike.com/download/client/c/4.1.7/
