### ISSUE TITLE
aerospike malloc handler

### ISSUE THREAD

**Issue by lathakris** [aerospike/aerospike-client-c#70]
Hi,

Is there a custom memory allocator we can use for aerospike ? point to our memory allocator instead of malloc ?

Thanks.

**Comment by bbulkow** [comment]
Client malloc calls go through the shim located at 
https://github.com/aerospike/aerospike-common/blob/master/src/main/citrusleaf/cf_alloc.c
which gives you a convenient location to call your own allocator. Since this is C, you can use a wide variety of techniques to override that.

**Comment by lathakris** [comment]
ok. thank you for the response.
