### ISSUE TITLE
Client doesn't clean up the CLOSE_WAIT sockets resulted from reaping the inactive connections on the server side

### ISSUE THREAD

**Issue by scoriiu** [aerospike/aerospike-client-c#73]
In order to save/recycle file descriptors, the server reaps the inactive connections once each `service.proto-fd-idle-ms` (60s by default). Yet, when the server closes the inactive connections, there is no mechanism in place to communicate the client about this action. This will result in sockets hanging on the client side in CLOSE_WAIT status. The sockets will eventually be closed/cleaned-up properly **only if** the client subsequently attempts to access the closed socket or if the application is closed. 
This might lead to a significant number of sockets being stuck in a deployment where there is no subsequent activity on these sockets.

One solution would be to create a handshake between server and client when the connections are being reaped which will properly close the sockets on both ends. Another quick-fix would be creating a function which periodically validate and close the invalid connections for each of the nodes as bellow:
```
void validate_and_close_connection(as_node* node) {
    uint32_t max = node->cluster->conn_pools_per_node;
    for (uint32_t i = 0; i < max; i++) {
        as_conn_pool_lock* pool_lock = &node->conn_pool_locks[i];
        as_socket sock;
        pthread_mutex_lock(&pool_lock->lock);
        int total = pool_lock->pool.total;
        int idx = 0;
        while (idx++ < total && as_conn_pool_get(&pool_lock->pool, &sock)) {
            if(as_socket_validate(&sock) == 0) {
                // valid, return conn to the pool
                as_conn_pool_put(&pool_lock->pool, &sock);
            } else {
                // invalid, close and remove conn from the pool
                as_socket_close(&sock);
                as_conn_pool_dec(&pool_lock->pool);
            }
        }
        pthread_mutex_unlock(&pool_lock->lock);
    }
}
```

On a separate note, making an aggregate query only one time, will protect the associated sockets being reaped due to inactivity from that moment onwards (see https://github.com/aerospike/aerospike-server/blob/1524f6373f25c4bc7d7ca09ecca52fe9e0d84ec4/as/src/base/thr_query.c#L2722)
Why not close these sockets as well and create new ones when there will be activity? At least have an option for it? This might save a significant number of sockets being wasted after all.

In my setup I use the following
aerospike-client-c-4.2.0
aerospike-server-community-3.11.1

**Comment by BrianNichols** [comment]
I think it is a good idea to validate/remove sockets that have been reaped by the server earlier than the current implementation, but we have to be very careful not to degrade performance.  The extra pool lock would severely degrade performance in async mode where connections are currently retrieved in single threaded (event loop thread) mode (no locks).

Closing/Reopening sockets is much more expensive that reusing sockets and should be avoided when possible.

I do agree that giving the user more control of socket pool management will help.   We will research possible solutions after our current projects are completed.
