### ISSUE TITLE
Debian 9 package

### ISSUE THREAD

**Issue by deric** [aerospike/aerospike-client-c#74]
Currently there's no package for [Debian 9](https://www.aerospike.com/download/client/c/4.2.0/) at downloads page. I've managed to build the client packages without any problems. Would it be possible to add Debian 9 to the package release pipeline?

**Comment by BrianNichols** [comment]
We will add Debian 9 support in a future release.

**Comment by deric** [comment]
Cool, thanks!

**Comment by BrianNichols** [comment]
C client 4.3.0 has been released which includes a Debian 9 package.

https://www.aerospike.com/download/client/c/4.3.0/
