### ISSUE TITLE
debian dev package bug in postinst script

### ISSUE THREAD

**Issue by jarda-manana** [aerospike/aerospike-client-c#75]
in postinst script in debian aerospike-client-c-devel packege is this line:
```chown -R aerospike:aerospike /opt/aerospike```

However the path does not exist if you haven't installed aerospike-client-c or aerospike-tools package.

**Comment by BrianNichols** [comment]
I had assumed that the previous lines in postinst would create the directory for you.
```
  if ! getent passwd aerospike >/dev/null; then
    useradd -r -d /opt/aerospike -g aerospike aerospike
  fi
```
I suppose if the aerospike user existed, but had a different home directory, then that would be a problem.  To be safe, I will add the following before the chown in the next release.

```
mkdir -p /opt/aerospike
```

**Comment by BrianNichols** [comment]
C client 4.3.0 has been released.

https://www.aerospike.com/download/client/c/4.3.0
