### ISSUE TITLE
compatibility issue with time.h on Windows platform

### ISSUE THREAD

**Issue by yongningcds** [aerospike/aerospike-client-c#76]
redefinition of "struct timespec" compile time error. This is more of Windows problem, but I resolved it by adding #define HAVE_STRUCT_TIMESPEC before #include <pthread.h>. 
Found solution here https://stackoverflow.com/questions/33557506/timespec-redefinition-error

**Comment by BrianNichols** [comment]
That is a known issue with the Windows pthread library.  If you download the C client via nuget package manager, HAVE_STRUCT_TIMESPEC  will automatically be defined for you.
