### ISSUE TITLE
API cause core dumps by referencing data that can be released by user

### ISSUE THREAD

**Issue by AlgoTrader** [aerospike/aerospike-client-c#8]
The following code make core dump:

    char *addr = *(String::Utf8Value(addrVal->ToString()));
    int port = portVal->Int32Value();
    as_config_add_host(&asConfig, addr, port);

The code is plain and simple. But we have a problem. char *addr is on stack and released on function exit. Why aerospike C client cannot make a deep copy of the hostname if it needs it for long time? The following code solve the problem, but is ugly:

    char *addr = *(String::Utf8Value(addrVal->ToString()));
    int port = portVal->Int32Value();
    as_config_add_host(&asConfig, strdup(addr), port);

**Comment by wchu-citrusleaf** [comment]
we've considered this, and currently have opted for easier api of not requiring a config_destroy().

Regarding additional crashes, we have made extensive fixes, including the up coming release. Please do let us know if there are additional issues you hit, and we will do our best to address them. Thanks.
