### ISSUE TITLE
as_arraylist memory leak

### ISSUE THREAD

**Issue by burlog** [aerospike/aerospike-client-c#90]
Steps to reproduce:

* create array list with zero capacity,
* put new element to i,
* destroy the list,
* the memory allocated for an array is not freed.

```
#include <aerospike/as_arraylist.h>

int main(int argc, char *argv[]) {
    as_arraylist list;
    as_arraylist_init(&list, 0, 8);
    as_arraylist_append_int64(&list, 3);
    as_arraylist_destroy(&list);
}
```

The static function `as_arraylist_ensure` in `modules/common/src/main/aerospike/as_arraylist.c` should probably also ensure that the `free` is set to true.

**Comment by BrianNichols** [comment]
This leak will be fixed in the next release.  The workaround is to not set initial capacity to zero.

**Comment by BrianNichols** [comment]
C client 4.6.9 has been released.

https://www.aerospike.com/download/client/c/4.6.9/
