### ISSUE TITLE
Misleading async batch API examples

### ISSUE THREAD

**Issue by maxim-ky** [aerospike/aerospike-client-c#98]
Hello.

AFAIC, there's a mistake in the async batch API examples regarding as_batch_read_record::bin_filter.
There's an example here https://github.com/aerospike/aerospike-client-c/blob/ccf05d928058c950f4db18bda21c67ce6fad8e8b/src/include/aerospike/aerospike_batch.h#L311
which states that ```bin_names can be placed on stack because it's only referenced before being queued on event loop```

But bin_names could be also accessed via ```as_batch_retry_async``` i.e. when the original stack variable is already destroyed. 

The same is implicitly stated here https://github.com/aerospike/aerospike-client-c/blob/bda70092be0b3e14c24b4debe96dd52f45c2a485/src/test/aerospike_batch/batch_get_async.c#L161

**Comment by BrianNichols** [comment]
The "stack" comment is wrong, but the example code is correct.  In the example code, the local variable "bins" points to a static array of literal strings.  The local variable falls out of scope on retry, but the static array of literal strings remains valid.

The comment will be fixed to say:

 * // bin_names must point to a static/global array of literal/global strings.

**Comment by maxim-ky** [comment]
Thanks!

I think the example would be totally clear if the bin_names lifetime was explicitly stated e.g. by dynamic allocation.
